---
- hosts: zimbra
  tasks:
   - name: Disable SELinux
     selinux:
       state: disabled

#   - name: be sure firewalld is installed
#     dnf: name=firewalld state=installed
#     tags:
#      - install
#      - firewalld
 
   - name: be sure firewalld is disabled
     systemd: name=firewalld enabled=no
     tags:
      - install
      - atomic
      - firewalld

   - name: be sure firewalld is stopped
     systemd: name=firewalld state=stopped
     ignore_errors: yes
     tags:
      - install
      - atomic
      - firewalld
